<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-N8OU8L6" ignored="6" name="Test(failed)" tests="2" failures="2" timestamp="15 Dec 2020 10:02:32 GMT" time="0.047" errors="0">
  <testcase name="TC7" time="0.012" classname="Org.testcases.TestNGRetry">
    <failure type="java.lang.AssertionError" message="Assertion message expected [expecting] but found [actual]">
      <![CDATA[java.lang.AssertionError: Assertion message expected [expecting] but found [actual]
at Org.testcases.TestNGRetry.TC7(TestNGRetry.java:21)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC7 -->
  <testcase name="TC2" time="0.002" classname="Org.testcases.TestNGRetryFeature">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Org.testcases.TestNGRetryFeature.TC2(TestNGRetryFeature.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase name="TC3" time="0.0" classname="Org.testcases.TestNGRetryFeature">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase name="TC4" time="0.0" classname="Org.testcases.TestNGRetryFeature">
    <ignored/>
  </testcase> <!-- TC4 -->
  <testcase name="TC1" time="0.0" classname="Org.testcases.TestNGRetryFeature">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase name="TC8" time="0.0" classname="Org.testcases.TestNGRetry">
    <ignored/>
  </testcase> <!-- TC8 -->
  <testcase name="TC5" time="0.0" classname="Org.testcases.TestNGRetry">
    <ignored/>
  </testcase> <!-- TC5 -->
  <testcase name="TC6" time="0.0" classname="Org.testcases.TestNGRetry">
    <ignored/>
  </testcase> <!-- TC6 -->
</testsuite> <!-- Test(failed) -->
